ECommerce.MVC/Models/ErrorViewModel.cs
namespace ECommerce.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerce.MVC/Areas/Administrator/Controllers/CategoryController.cs
using ECommerce.BLL.Repositories.Abstracts;
using ECommerce.BLL.ViewModels.CategoryViewModels;
using ECommerce.Model.Entities;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.MVC.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        //todo:Icategoryservice içerisinde bulunan GetActiveCategories isimli metot tarafından iletilen veriler index sayfasında gösterilecek.

        public CategoryController(ICategoryService categoryService) 
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var categories=_categoryService.GetActiveCategories().OrderByDescending(x=>x.CreatedDate).Select(x=>new CategoryListViewModel
            {
                Id=x.ID,
                CategoryName=x.CategoryName,
                Description=x.Description,
                IsActive=x.IsActive,
                Status=x.Status
            }).ToList();

            return View(categories);
        }

        //create

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel categoryViewModel)
        {
            if(ModelState.IsValid)
            {
                Category category = new Category()
                {
                    CategoryName = categoryViewModel.CategoryName,
                    Description = categoryViewModel.Description,
                };
              string result= await _categoryService.CreateCategory(category);
                TempData["Result"] = result;
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View(categoryViewModel);
            }
            
        }
        //update
        //Get: Update Category
        [HttpGet]
        public IActionResult Update(int id)
        {
            var updated = _categoryService.GetCategoryById(id);

            if (updated != null)
            {
                return View(updated);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }
        //Post: Update Category
        [HttpPost]
        public async Task<IActionResult> Update(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            string result = await _categoryService.UpdateCategory(category);

            TempData["result"] = result;

            return RedirectToAction("Index", "Category");

        }


        //delete
        //deatails: bu işlemi en sona bıraktık
        //destroy
        //getpassiveCategories
    }
}

ECommerce.MVC/Areas/Administrator/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.MVC.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ECommerce.MVC/Areas/Administrator/Controllers/ProductController.cs
using ECommerce.BLL.Repositories.Abstracts;
using ECommerce.BLL.ViewModels.CategoryViewModels;
using ECommerce.BLL.ViewModels.ProductViewModels;
using ECommerce.Common.ImageHelper;
using ECommerce.Model.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace ECommerce.MVC.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductController(IProductService productService,ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var products = _productService.GetAllProducts().Select(x => new ProductViewModel
            {
                ProductId = x.ID,
                ProductName = x.ProductName,
                UnitPrice = x.UnitPrice,
                UnitsInStock = x.UnitsInStock,
                CategoryId = x.CategoryId,
                Status = x.Status,
                ImagePath = x.ImagePath,
            }).ToList();

            return View(products);
        }

        //create product
        
        public IActionResult Create()
        {
            //AutoMapper'ı kullanımını araştır

            //AutoMapper: model ile ilişkili olan nesneleri otomatik olarak dönüştürülmesini sağlayan bir kütüphanedir.
            ViewBag.CategoryListItem = _categoryService.GetAllCategories().Select(x => new CategoryViewModel
            {
                CategoryName = x.CategoryName,
                Description = x.Description,
                Id = x.ID

            }).Select(s => new SelectListItem
            {
                Text = s.CategoryName,
                Value = s.Id.ToString()
            });
           

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel productViewModel, IFormFile productImage)
        {
            if (ModelState.IsValid)
            {

                var ImageEditResult = ImageHelper.Upload(productImage.FileName);

                if (ImageEditResult == "0")
                {
                    TempData["Error"] = "Görsel izin verilen formatta değil";
                    return View();
                }
                else
                {
                    //multimedia ları system.IO kütüphanesi ile kayıt edebilmemize olanak sağlıyor.
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\products", ImageEditResult);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        productImage.CopyToAsync(stream);
                    }


                    Product product = new Product
                    {
                        ID = productViewModel.ProductId,
                        ProductName = productViewModel.ProductName,
                        UnitPrice = productViewModel.UnitPrice,
                        UnitsInStock = productViewModel.UnitsInStock,
                        CategoryId = productViewModel.CategoryId,
                        Status = productViewModel.Status,
                        ImagePath = ImageEditResult
                    };

                    var result = await _productService.CreateProductAsync(product);

                    return RedirectToAction("Index", "Home");
                }


            }
            else
            {
                return View(productViewModel);
            }

        }
    }
}

ECommerce.MVC/Controllers/CategoryController.cs
using ECommerce.BLL.Repositories.Abstracts;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var categories= _categoryService.GetAllCategories();

            return View();
        }
    }
}

ECommerce.MVC/Controllers/HomeController.cs
using ECommerce.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerce.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerce.MVC/Areas/Administrator/Views/Category/Create.cshtml
@model ECommerce.BLL.ViewModels.CategoryViewModels.CategoryViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
}

<h1>Create</h1>
<form method="post">
    <div>
        <label asp-for="CategoryName"></label>
        <input type="text" asp-for="CategoryName"/>
    </div>
    <div>
        <label asp-for="Description"></label>
        <input type="text" asp-for="Description" />
    </div>
    <button type="submit">Oluştur</button>
</form>

ECommerce.MVC/Areas/Administrator/Views/Category/Index.cshtml
@model List<CategoryListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
}

<h1>Area Category Index</h1>

<table>
    <tr>
        <th>ID</th>
        <th>CategoryName</th>
        <th>Description</th>
        <th>Is Active</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.CategoryName</td>
            <td>@item.Description</td>
            <td>
                @*  @if (item.IsActive)
            {
            <span>Aktif</span>
            }else
            {
            <span>Pasif</span>
            } *@

                <!--Ternary If: tek satırda karar yapısı kullanımı-->
                @{
                    string result = item.IsActive ? "Aktif" : "Pasif";
                    <span>@result</span>
                }
            </td>
            <td>
                @switch (item.Status)
                {
                    case ECommerce.Model.Enums.DataStatus.DELETED:
                        <span>Silinmiş</span>
                        break;

                    case ECommerce.Model.Enums.DataStatus.UPDATED:
                        <span>Güncellenmiş</span>
                        break;

                    case ECommerce.Model.Enums.DataStatus.INSERTED:
                        <span>Eklendi</span>
                        break;

                }
            </td>
            <td>
                <a asp-action="Update" asp-controller="Category" asp-route-id="@item.Id">Update</a>
                <a asp-action="Delete" asp-area="Administrator" asp-controller="Category" asp-route-id="@item.Id">Delete</a>

            </td>
        </tr>
    }
</table>

ECommerce.MVC/Areas/Administrator/Views/Category/Update.cshtml
@model CategoryListViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
}

<h1>Update</h1>
<form method="post">
    <div>
        <label asp-for="CategoryName"></label>
        <input type="text" asp-for="CategoryName" />
    </div>
    <div>
        <label asp-for="Description"></label>
        <input type="text" asp-for="Description" />
    </div>
    <div>
        <label asp-for="IsActive"></label>
        <input type="checkbox" asp-for="IsActive" name="IsActive" checked />
    </div>
    <button type="submit">Güncelle</button>
</form>

ECommerce.MVC/Areas/Administrator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
   // string result = TempData["Result"] as string;
}

@if (TempData["Result"] != null)
{
    <div>
        <span>@TempData["Result"]</span>
    </div>
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Starter Page</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="content">
    <div class="container-fluid">
        <div class="row">
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

ECommerce.MVC/Areas/Administrator/Views/Product/Create.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
}

<form method="post" enctype="multipart/form-data">
    <div>
        <label asp-for="ProductName"></label>
        <input class="form-control" type="text" asp-for="ProductName" />
    </div>
    <div>
        <label asp-for="UnitPrice"></label>
        <input class="form-control" type="number" asp-for="UnitPrice" />
    </div>
    <div>
        <label asp-for="UnitsInStock"></label>
        <input class="form-control" type="number" asp-for="UnitsInStock" />
    </div>
    <div>
        <!--Burada bir select list oluşturularak bütün kategoriler listelenecek.Modelimizde category olmadığı için selecte categoryiye iletmek için farklı bir taşıyıcı model oluşturmamız gerekiyor. Yada hazır modelimizde categoryiyi liste şeklinde productviewmodele ekleyerek bunu sağlayabiliriz.-->
        <select class="form-control" asp-items="@ViewBag.CategoryListItem" asp-for="CategoryId">
            <option selected="" disabled>Select Category</option>
        </select>


    </div>

    <div>
        <input class="form-control" type="file" name="productImage" />
    </div>

    <button class="btn btn-success" type="submit">Oluştur</button>
</form>

ECommerce.MVC/Areas/Administrator/Views/Product/Index.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "Ürün Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml";
}

<a class="btn btn-primary"  asp-action="Create" asp-controller="Product">Yeni Ürün Ekle</a>
<table class="table table-hover">
    <tr>
        <th>Image</th>
        <th>ID</th>
        <th>ProductName</th>
        <th>UnitPrice</th>
        <th>Stock</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.ImagePath != null)
                {
                    <img src="~/images/products/@item.ImagePath" width="72" height="72" />
                }
                else
                {
                    <img src="https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png" width="72" height="72" />
                }


            </td>
            <td>@item.ProductId</td>
            <td>@item.ProductName</td>
            <td>@item.UnitPrice</td>
            <td>@item.UnitsInStock</td>

            <td>
                @switch (item.Status)
                {
                    case ECommerce.Model.Enums.DataStatus.DELETED:
                        <span>Silinmiş</span>
                        break;

                    case ECommerce.Model.Enums.DataStatus.UPDATED:
                        <span>Güncellenmiş</span>
                        break;

                    case ECommerce.Model.Enums.DataStatus.INSERTED:
                        <span>Eklendi</span>
                        break;

                }
            </td>
            <td>
                <a asp-action="Update"  asp-controller="Product" asp-route-id="@item.ProductId">Update</a>
                <a asp-action="Delete" asp-area="Administrator" asp-controller="Product" asp-route-id="@item.ProductId">Delete</a>

            </td>
        </tr>
    }
</table>

ECommerce.MVC/Areas/Administrator/Views/Shared/_AdministratorLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AdministratorLayout</title>
    <link href="~/AdminLteTemplate/css/adminlte.css" rel="stylesheet"/>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLteTemplate/plugins/fontawesome-free/css/all.min.css">


</head>
<body>
    <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="index3.html" class="nav-link">Home</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Navbar Search -->
            <li class="nav-item">
                <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                    <i class="fas fa-search"></i>
                </a>
                <div class="navbar-search-block">
                    <form class="form-inline">
                        <div class="input-group input-group-sm">
                            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                    <i class="fas fa-times"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <!-- Messages Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-comments"></i>
                    <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Brad Diesel
                                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">Call me whenever you can...</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <!-- Message Start -->
                        <div class="media">
                            <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                        <!-- Message End -->
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
            </li>
            <!-- Notifications Dropdown Menu -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                    <i class="fas fa-th-large"></i>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
            <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">AdminLTE 3</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">Alexander Pierce</a>
                </div>
            </div>

            <!-- SidebarSearch Form -->
            <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item menu-open">
                        
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="category" class="nav-link active">
                                    <i class="fa fa-list-ul"></i>
                                    <p>Categories</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="product" class="nav-link">
                                    <i class="fa fa-list-ul"></i>
                                    <p>Products</p>
                                </a>
                            </li> <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-list-ul"></i>
                                    <p>Suppliers</p>
                                </a>
                            </li> </li> <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-list-ul"></i>
                                    <p>Orders</p>
                                </a>
                            </li> </li> </li> <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-list-ul"></i>
                                    <p>Order Details</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                   
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @RenderBody()


        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
            <h5>Title</h5>
            <p>Sidebar content</p>
        </div>
    </aside>
    <!-- /.control-sidebar -->
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>
    </div>
    <!-- ./wrapper -->


    <script src="~/AdminLteTemplate/js/adminlte.js"></script>
    <script src="~/AdminLteTemplate/js/demo.js"></script>
</body>
</html>

ECommerce.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerce.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ECommerce.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>